### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by rjc**

### CODE REVIEW

**Comment by CendioOssman** [comment]
That link works just fine for me. What problem are you seeing?

**Comment by rjc** [comment]
$ curl -o /dev/null -sIw "%{http_code}\t%{redirect_url}\t%{url_effective}\n" "https://mid.mail-archive.com/alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se"
    404             https://mid.mail-archive.com/alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se

**Comment by CendioOssman** [comment]
Yeah, it seems like that function is broken using https. However our link uses http, so it should work fine for you.

I double checked if they are using some other mechanism, but their documentation still refers to using http. You might want to ping them and see if the lack of https support is a bug or not.

**Comment by rjc** [comment]
Sorry, you lost me there - the link on your website uses plain _HTTP_. Said URL then redirects, with a _302_ HTTP status code, to _HTTPS_ version which, in turn, returns _404_. I don't see any way to view that message in that mailing list archive but I easily found a copy on [_MARC_](https://marc.info/), which I use for all mailing list archives as it's more reliable and it simply doesn't suck ;^)

It's simply disappointing to read:

> More information regarding the motivation for creating this project can be found in the project announcement.

without actually being able to read the _project announcement_, hence the PR :^)

**Comment by CendioOssman** [comment]
The redirect is to https, yes. But it is also to an entirely different URL:

```console
$ curl -o /dev/null -sIw "%{http_code}\t%{redirect_url}\t%{url_effective}\n" "http://mid.mail-archive.com/alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se"
302	https://www.mail-archive.com/search?l=mid&q=alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se	http://mid.mail-archive.com/alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se
$ curl -o /dev/null -sIw "%{http_code}\t%{redirect_url}\t%{url_effective}\n" "https://www.mail-archive.com/search?l=mid&q=alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se"
302	https://www.mail-archive.com/vnc-list@realvnc.com/msg27308.html	https://www.mail-archive.com/search?l=mid&q=alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se
$ curl -o /dev/null -sIw "%{http_code}\t%{redirect_url}\t%{url_effective}\n" "https://www.mail-archive.com/vnc-list@realvnc.com/msg27308.html"
200		https://www.mail-archive.com/vnc-list@realvnc.com/msg27308.html
```

**Comment by CendioOssman** [comment]
Is this not the path your browser follows?

**Comment by rjc** [comment]
Right, I got to the bottom of this - it's the [DuckDuckGo Privacy Essentials add-on](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/) that's causing it. Also, rather than actually using the URL which I got from `curl`, I was copying it from the web browser's address bar after redirect thinking they're the same ;^)... sorry.

Either way, could we simply go away with all the redirects and use the final URL, please? :^)

Or, if you'd still like to use a link which has the Message-ID, then this one works just fine even with the add-on enabled:

https://marc.info/?i=alpine.LFD.2.00.0902271116020.25749%20()%20maggie%20!%20lkpg%20!%20cendio%20!%20se

:^D

**Comment by CendioOssman** [comment]
I'm afraid that's something you'll have to report to DuckDuckGo in that case. Or ask mail archive if they can enable that feature over https as well.

**Comment by rjc** [comment]
Yes, I'll do that.

However, the question remains - is there any reason why you simply don't go away with all the HTTP redirects and use the final URL?

Like I've also mentioned above, if you'd like to use the _Message-ID_ header there, then the _MARC_ copy works just fine, too.

**Comment by CendioOssman** [comment]
It is indeed to get the message ID in there as that is likely more stable even if mail archive decide to reorganise things. And I don't see it as reasonable to switch to MARC just because DuckDuckGo happens to have an incompatible extension.

**Pull request closed without merging**
